---
title: "wdpar: Interface to the World Database on Protected Areas"
tags:
  - R
  - conservation planning
  - protected areas
  - reserves
  - marine protected areas
  - other effective area-based conservation measures
  - spatial prioritization
authors:
  - name: Jeffrey O. Hanson
    orcid: 0000-0002-4716-6134
    affiliation: 1
affiliations:
 - name: Department of Biology, Carleton University, Ottawa, Canada
   index: 1
date: "`r format(Sys.time(), '%d %B %Y')`"
bibliography: paper.bib
output: rticles::joss_article
journal: JOSS
link-citations: yes
---

# Summary

The \texttt{wdpar} \texttt{R} package provides an interface to data available on Protected Planet (https://www.protectedplanet.net). It can be used to access the World Database on Protected Areas (WDPA) and the World Database on Other Effective Area-Based Conservation Measures (WDOECM). Additionally, it provides data cleaning procedures to prepare these databases for analysis. These data cleaning procedures are essential for ensuring correct results when using the databases. As a software package for the \texttt{R} statistical computing environment, it can easily be integrated into workflows and spatial analyses. The package has applications for conservation research. It has been used to assess performance of existing protected areas and account for such areas when identifying priority areas for conservation efforts.

# Statement of need

Area-based conservation measures are crucial for safeguarding biodiversity [@r5; @r6]. Examples of such measures include protected areas, marine reserves, and other effective area-based conservation measures (OECMs). Protected Planet is a key resource for area-based conservation measures, providing the World Database on Protected Areas (WDPA) and the World Database on Other Effective Area-Based Conservation Measures (WDOECM) [@r9]. These publicly available databases contain standardized data for over 270,000 protected areas and over 700 OECMs worldwide [@r9]. By detailing the designation, establishment, management, and spatial boundaries of area-based conservation measures [@r21], these databases play a vital role in monitoring and prioritizing conservation efforts [@r4; @r8].

The WDPA and WDOECM require data cleaning procedures to prepare them for analysis [@r4; @r10]. These procedures include excluding areas that have yet to be fully implemented, areas that are no longer designated, and UNESCO Biosphere Reserves [@r1]. They also include geoprocessing procedures, such as repairing invalid geometries in spatial boundaries, buffering areas represented by point localities [@r3], and removing spatial overlaps [@r2]. Specifically, overlapping geometries are erased such that areas associated with more effective management categories are retained [@r22] and -- in cases where geometries with the same management category overlap -- areas associated with historical precedence are retained. These procedures are critical to ensure accuracy in assessments of area-based conservation measures [@r1; @r2]. Yet, despite their importance, these procedures can be challenging to implement.

The \texttt{wdpar} \texttt{R} package provides automated methods to obtain and clean the WDPA and WDOECM. The data cleaning procedures implemented in the package follow best practices [@r4; @r10] and can be performed without specialized knowledge, customized to particular use cases, and applied to the global scale. By providing this functionality, the package aims to increase accessibility to the WDPA and WDOECM.

# Applications

The \texttt{wdpar} \texttt{R} package is designed to provide a reproducible tool for downloading and cleaning the WDPA and WDOECM. Although the default settings for the data cleaning procedures are well-suited for national scale reporting of protected area coverage, they can be customized for other applications. For example, the precision of spatial data processing procedures can be increased so that they are suitable for local scale analyses. This is especially important because the default precision may remove smooth edges at fine scales. Additionally, the data cleaning procedures can be customized to retain protected areas regardless of their status which, in turn, could be useful for monitoring and evaluation of protected area effectiveness.

The \texttt{wdpar} \texttt{R} package has several applications for conservation research. For example, it has been used to assess the performance of existing protected areas in Colombia, Greece, and South Asia [@r11; @r16; @r13; @r17]. It has also been used to examine the potential implications of climate change on conservation efforts [@r12; @r14]. Additionally, it has been used to account for existing protected areas when identifying priority areas for biodiversity conservation [@r15]. Furthermore, it has been used to help understand how protected area management by Indigenous Peoples can reduce deforestation [@r18].

# Comparison with other software packages

The \texttt{wdpar} \texttt{R} package provides superior functionality for processing Protected Planet data compared with other software packages. Although the \texttt{rwdpa} \texttt{R} package, \texttt{worldpa} \texttt{R} package, and the \texttt{pywdpa} \texttt{Python} package provide interfaces for downloading data from Protected Planet [@r23; @r24; @r25], none of these software packages provide functionality for data cleaning. Additionally, the \texttt{rwdpa} \texttt{R} package has been archived. A command line tool was also developed to download and clean Protected Planet data [@r26]. However, because the command line tool was implemented as a collection of \texttt{Python} scripts and configuration files, it is difficult to install and customize.

# Availability

The \texttt{wdpar} \texttt{R} package is implemented as a software package for \texttt{R} statistical computing environment [@r19]. It is available on the Comprehensive R Archive Network (CRAN) [@r20]. Developmental versions are available on an online code repository (<https://github.com/prioritizr/wdpar>). Documentation for the package is also available online (<https://prioritizr.github.io/wdpar>).

# Acknowledgments

The author thanks all of the individuals that have contributed to the package by reporting software defects and providing suggestions to improve functionality. The author is also grateful to Joseph Bennett for feedback on a draft of the manuscript. The author was supported by Environment and Climate Change Canada (ECCC) and Nature Conservancy of Canada (NCC).

# Conflict of interest

The author declares no conflict of interest.

# References
